"""Generate the browsable database pages under atlas/databases/ from the JSONL databases.

These pages are regenerated on every build; edit the JSONL, never the pages.
"""
from collections import defaultdict
from pathlib import Path

from . import db

HEADER = "> Generated by `python -m irs build` from `databases/*.jsonl`. Do not edit by hand.\n"


def _c(v) -> str:
    if v is None:
        return ""
    if isinstance(v, list):
        v = ", ".join(map(str, v))
    return str(v).replace("|", "\\|").replace("\n", " ")


def _table(cols: list, rows: list) -> str:
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    out += ["| " + " | ".join(_c(x) for x in r) + " |" for r in rows]
    return "\n".join(out)


def _links(ids: list, sources: dict) -> str:
    return " ".join(f"[{i}]({sources[i]['url']})" if i in sources else i for i in ids or [])


def build(ind: Path) -> list:
    dbs = db.load_all(ind)
    S = db.index(dbs["sources"])
    C = db.index(dbs["claims"])
    out_dir = ind / "atlas" / "databases"
    out_dir.mkdir(parents=True, exist_ok=True)
    pages = {}

    by_ru = defaultdict(list)
    for c in dbs["claims"]:
        by_ru[c["research_unit"]].append(c)
    ru_titles = {u["id"]: u["title"] for u in dbs["research_units"]}
    body = []
    for ru in sorted(by_ru, key=db.id_num):
        body += [f"## {ru}: {ru_titles.get(ru, '')}", "", _table(
            ["ID", "Claim", "Type", "Status", "Confidence", "Sources", "Evidence"],
            [[c["id"], c["claim"], c["claim_type"], c["status"], c["confidence"], _links(c["source_ids"], S),
              c["evidence"][:300]] for c in by_ru[ru]]), ""]
    pages["claims-ledger"] = ("Claims ledger", "\n".join(body))

    metrics = [c for c in dbs["claims"] if c.get("metric")]
    pages["metrics"] = ("Metrics database", "Never compare two rows unless unit, period, geography and population match.\n\n" + _table(
        ["Claim", "Metric", "Value", "Unit", "Period", "Geography", "Population", "Methodology", "Confidence", "Sources"],
        [[c["id"], c["metric"]["name"],
          c["metric"]["value"] if c["metric"]["value"] is not None
          else f"{c['metric'].get('value_low', '?')}–{c['metric'].get('value_high', '?')}",
          c["metric"]["unit"], c["metric"]["period"], c["metric"]["geography"], c["metric"]["population"],
          c["metric"]["methodology"], c["confidence"], _links(c["source_ids"], S)] for c in metrics]))

    pages["companies"] = ("Company database", _table(
        ["ID", "Company", "Roles", "HQ", "Founded", "Ownership", "Stage", "Business model", "Products", "Metric claims", "Sources", "Last verified"],
        [[c["id"], c["name"], c["roles"], c["hq_country"], c.get("founded"), c.get("ownership"), c.get("stage"),
          c.get("business_model"), c.get("products"), c.get("metric_claim_ids"), _links(c["source_ids"], S),
          c["last_verified"]] for c in dbs["companies"]]))

    pages["regulations"] = ("Regulatory database", _table(
        ["ID", "Regulation", "Authority", "Jurisdiction", "Type", "Effective", "Status", "Affects", "Requirement", "Operational impact", "Penalties", "Sources"],
        [[r["id"], r["name"], r["authority"], r["jurisdiction"], r["instrument_type"], r.get("effective_date"), f"{r['status']} (as of {r['status_as_of']})",
          r["affected_participants"], r["requirements"], r.get("operational_impact"), r.get("penalties"),
          _links(r["source_ids"], S)] for r in dbs["regulations"]]))

    body = []
    for tier, label in ((1, "Tier 1: primary"), (2, "Tier 2: high-quality secondary"), (3, "Tier 3: discovery")):
        rows = [s for s in dbs["sources"] if s["tier"] == tier]
        body += [f"## {label} ({len(rows)})", "", _table(
            ["ID", "Title", "Publisher", "Published", "Accessed", "Type", "Paywalled"],
            [[s["id"], f"[{_c(s['title'])}]({s['url']})", s["publisher"], s["publication_date"], s["access_date"],
              s["source_type"], s.get("paywalled", "")] for s in rows]), ""]
    pages["sources"] = ("Source library", "\n".join(body))

    pages["documents"] = ("Key documents", _table(
        ["ID", "Document", "Publisher", "Date", "Type", "Why important", "Research units"],
        [[s["id"], f"[{_c(s['title'])}]({s['url']})", s["publisher"], s["publication_date"],
          s.get("doc_type", s["source_type"]), s.get("why_important"), s.get("research_units")]
         for s in dbs["sources"] if s.get("key_document")]))

    pages["glossary"] = ("Glossary", "\n\n".join(
        f"### {t['term']}\n\n**In plain words:** {t['simple_definition']}\n\n**Technically:** {t['technical_definition']}"
        + (f"\n\n**Example:** {t['example']}" if t.get("example") else "")
        + (f"\n\n**Related:** {', '.join(t['related_terms'])}" if t.get("related_terms") else "")
        + (f"\n\n**Sources:** {_links(t.get('source_ids'), S)}" if t.get("source_ids") else "")
        for t in sorted(dbs["glossary"], key=lambda t: t["term"].lower())))

    body = []
    for x in dbs["contradictions"]:
        body += [f"## {x['id']}: {x['topic']} ({x['status']})", "", x["disagreement"], "",
                 _table(["Claim", "Says", "Sources", "Confidence"],
                        [[i, C[i]["claim"], _links(C[i]["source_ids"], S), C[i]["confidence"]] for i in x["claim_ids"] if i in C]),
                 "", "**Possible reasons:** " + "; ".join(x["possible_reasons"]),
                 f"**More defensible:** {x.get('more_defensible') or 'not determinable'}. {x.get('rationale', '')}",
                 f"**Remaining uncertainty:** {x['remaining_uncertainty']}", ""]
    pages["contradictions"] = ("Contradiction ledger", "\n".join(body))

    unknowns = [c for c in dbs["claims"] if c["status"] == "unknown"]
    open_q = [(u["id"], q) for u in dbs["research_units"] for q in u.get("open_questions", [])]
    pages["knowledge-gaps"] = ("Knowledge gap report",
        "## Documented unknowns\n\n" + _table(["Claim", "What we could not establish", "Unit"],
                                             [[c["id"], c["claim"], c["research_unit"]] for c in unknowns])
        + "\n\n## Open questions from research units\n\n" + _table(["Unit", "Question"], open_q))

    body = []
    by_role = defaultdict(list)
    for i in dbs["interview_queue"]:
        by_role[i["who_can_answer"][0]].append(i)
    for role in sorted(by_role):
        body += [f"## Interview guide: {role}", "", _table(
            ["ID", "Question", "Why it matters", "What would resolve it", "Status"],
            [[i["id"], i["question"], i["why_it_matters"], i["resolving_evidence"], i["status"]] for i in by_role[role]]), ""]
    pages["interview-pack"] = ("Interview research pack", "Answers from interviews are recorded as claims of type "
                               "`reported_claim`, never as verified public evidence.\n\n" + "\n".join(body))

    pages["research-tree"] = ("Research tree", _table(
        ["ID", "Wave", "Pri", "Dimension", "Title", "Status", "Depends on", "Origin"],
        [[u["id"], u["wave"], u["priority"], u["dimension"], u["title"], u["status"], u.get("depends_on"), u["origin"]]
         for u in sorted(dbs["research_units"], key=lambda u: db.id_num(u["id"]))]))

    names = {r["id"]: r.get("name") for k in ("entities", "companies", "regulations") for r in dbs[k]}
    pages["knowledge-graph"] = ("Knowledge graph edges", _table(
        ["Subject", "Relation", "Object", "Evidence"],
        [[f"{names.get(r['subject_id'], '')} ({r['subject_id']})", r["predicate"],
          f"{names.get(r['object_id'], '')} ({r['object_id']})", r.get("claim_ids")] for r in dbs["relations"]])
        + "\n\n## Entities\n\n" + _table(["ID", "Name", "Type", "Description"],
                                        [[e["id"], e["name"], e["entity_type"], e["description"]] for e in dbs["entities"]]))

    written = []
    for slug, (title, text) in pages.items():
        p = out_dir / f"{slug}.md"
        p.write_text(f"# {title}\n\n{HEADER}\n{text}\n")
        written.append(p)
    idx = ["# Databases", "", HEADER] + [f"- [{t}]({s}.md)" for s, (t, _) in pages.items()]
    (out_dir / "README.md").write_text("\n".join(idx) + "\n")
    return written
