"""Reproducible opportunity scoring from config.yaml weights. No LLM arithmetic."""
from pathlib import Path

from . import db


def score_all(ind: Path) -> list:
    cfg = db.load_yaml(ind / "config.yaml").get("scoring", {})
    criteria = cfg.get("criteria", [])
    if not criteria:
        raise SystemExit("config.yaml has no scoring.criteria")
    total_w = sum(c["weight"] for c in criteria)
    results = []
    for o in db.load_db(ind, "opportunities"):
        rows, points = [], 0.0
        for c in criteria:
            inp = o["inputs"][c["id"]]
            v = inp["value"] if c.get("direction", "higher_is_better") == "higher_is_better" else 5 - inp["value"]
            p = c["weight"] * v
            points += p
            rows.append({"criterion": c["name"], "evidence": ", ".join(inp.get("evidence_claim_ids", [])) or "none",
                         "input": inp["value"], "weight": c["weight"],
                         "calculation": f"{c['weight']} x {v}" + ("" if v == inp["value"] else f" (5 - {inp['value']})"),
                         "result": p})
        score = round(100 * points / (5 * total_w), 1)
        results.append({"id": o["id"], "title": o["title"], "score": score, "rows": rows,
                        "formula": f"100 x {points:g} / (5 x {total_w:g}) = {score}"})
    return sorted(results, key=lambda r: -r["score"])


def to_markdown(results: list) -> str:
    out = ["# Opportunity scores", "", "Generated by `python -m irs score`. Inputs live in databases/opportunities.jsonl; "
           "weights in config.yaml. Edit those, never this page.", ""]
    for r in results:
        out += [f"## {r['id']}: {r['title']} ({r['score']})", "",
                "| Criterion | Evidence | Input | Weight | Calculation | Result |", "|---|---|---|---|---|---|"]
        out += [f"| {x['criterion']} | {x['evidence']} | {x['input']} | {x['weight']} | {x['calculation']} | {x['result']:g} |"
                for x in r["rows"]]
        out += ["", f"Score: {r['formula']}", ""]
    return "\n".join(out)
